language: java

jdk:
  - openjdk7
  - oraclejdk7

env:
  global:
    secure: gC3BXvfE0ALkeXWaxm4Qu7C/9jBWKKg1x7m5Sp5RwaKhYapi0VLCauB1C0wc6vggbnXPP6pPBsPaP7nXhRDMEjlO47CXmuYEXUsDLDuGQ6oQ+MPSKAZL47D3f5jKfL9G2FBAQZrCoU15vbmlKfXon3ftNL3QOaFgefN/nv7qQbM=
    secure: "NUw4/gAEv2+z/qXBFpwK4TKoQnnSzloM/7AfiH3+GaFBW8nVSO0raPVykShViVTdrJZFEr1Vez1dWUB8yvn6i3Ox6O2+38KBEw/wsxxljiYK+nUIBRbnO7PLOFu1B2ImmNM3MvxuESAPZpZd9QQpvCALsHVWqTiq9CSvpeqLcwc="
    secure: "TWhzNDZ+i9FW0Wru+qmSX1FoI0ESeeXTOSdRubWJIp2GT2eC4BlRgjYRuQ+Cn9nayCP0vTSrxXYLVQhOE0RFO/r8IdHg1C05HW8JallnShvlU51QdHgCSIPy3xKtB98c87H2ribwoJoIuCIx7yjKcmBhzGZXPW8bIkpolW8Pf1E="

after_success: ./build/deploy.sh